const i18n = {
    ar: {
        "share": "مشاركة",
        "days": "يوم",
        "hours": "ساعة",
        "mins": "دقيقة",
        "secs": "ثانية",
        "notify": "تفعيل التنبيهات",
        "ramadan-title": "شهر رمضان المبارك",
        "ramadan-date": "1 رمضان 1447 هـ | 18 فبراير 2026 م",
        "eid1-title": "عيد الفطر المبارك",
        "eid1-date": "1 شوال 1447 هـ | 20 مارس 2026 م",
        "hajj-title": "عشر ذي الحجة",
        "hajj-date": "1 ذو الحجة 1447 هـ | 18 مايو 2026 م",
        "eid2-title": "عيد الأضحى المبارك",
        "eid2-date": "10 ذو الحجة 1447 هـ | 27 مايو 2026 م",
        "v1": "﴿شَهرُ رَمَضانَ الَّذي أُنزِلَ فيهِ القُرآنُ هُدًى لِلنّاسِ وَبَيِّناتٍ مِنَ الهُدى وَالفُرقانِ فَمَن شَهِدَ مِنكُمُ الشَّهرَ فَليَصُمهُ وَمَن كانَ مَريضًا أَو عَلى سَفَرٍ فَعِدَّةٌ مِن أَيّامٍ أُخَرَ يُريدُ اللَّهُ بِكُمُ اليُسرَ وَلا يُريدُ بِكُمُ العُسرَ وَلِتُكمِلُوا العِدَّةَ وَلِتُكَبِّرُوا اللَّهَ عَلى ما هَداكُم وَلَعَلَّكُم تَشكُرونَ﴾",
        "v1-ref": "[البقرة: ١٨٥]", 
        "v2": "﴿الحَجُّ أَشهُرٌ مَعلوماتٌ فَمَن فَرَضَ فيهِنَّ الحَجَّ فَلا رَفَثَ وَلا فُسوقَ وَلا جِدالَ فِي الحَجِّ وَما تَفعَلوا مِن خَيرٍ يَعلَمهُ اللَّهُ وَتَزَوَّدوا فَإِنَّ خَيرَ الزّادِ التَّقوى وَاتَّقونِ يا أُولِي الأَلبابِ﴾",
        "v2-ref": "[البقرة: ١٩٧]",
        "lang-btn": "English",
        "theme-btn": "نمط",
        "copy-msg": "تم نسخ التفاصيل بنجاح!"
    },
    en: {
        "share": "Share",
        "days": "Days",
        "hours": "Hrs",
        "mins": "Min",
        "secs": "Sec",
        "notify": "Notifications",
        "ramadan-title": "Holy Ramadan",
        "ramadan-date": "Feb 18, 2026",
        "eid1-title": "Eid Al-Fitr",
        "eid1-date": "March 20, 2026",
        "hajj-title": "10 Days of Dhu al-Hijjah",
        "hajj-date": "May 18, 2026",
        "eid2-title": "Eid Al-Adha",
        "eid2-date": "May 27, 2026",
        "v1": "“The month of Ramadhan [is that] in which was revealed the Qur'an, a guidance for the people and clear proofs of guidance and criterion. So whoever sights [the new moon of] the month, let him fast it...”",
        "v1-ref": "[Al-Baqarah: 185]",
        "v2": "“Hajj is [during] well-known months, so whoever has made Hajj obligatory upon himself therein, there is [to be for him] no disobedience and no disputing during Hajj...”",
        "v2-ref": "[Al-Baqarah: 197]",
        "lang-btn": "عربي",
        "theme-btn": "Theme",
        "copy-msg": "Details copied successfully!"
    }
};
